"""
Knowledge Center - Educational Content for ARUN Bot
Provides strategy guides, tooltips, and explanations for non-technical users.
"""

STRATEGY_GUIDES = {
    "CAPABILITIES_SUMMARY": {
        "title": "🌟 ARUN Bot Capabilities (v2.0)",
        "summary": "Quick overview of what this bot can do.",
        "how_it_works": [
            "1. Auto-Login 🔐",
            "   - Secure, password-less login via TOTP. No manual daily token entry.",
            "",
            "2. Smart Dashboard 📊",
            "   - Real-time tracking of Positions, Orders, and P&L.",
            "   - 'Funds' card shows Real vs Allocated capital.",
            "",
            "3. Safety First 🛡️",
            "   - 'Panic Button' to cancel all orders/exit positions instantly.",
            "   - 'Resync' button to fix data if you trade on your phone.",
            "",
            "4. Live Scanning 📡",
            "   - Monitors RSI for 50+ stocks simultaneously.",
            "   - Checks Market Status (Open/Closed) automatically."
        ]
    },
    "BROKER_SETUP": {
        "title": "🔌 Broker Setup (API Keys & Tokens)",
        "summary": "Step-by-step guide to getting your keys.",
        "how_it_works": [
            "--- mStock (Mirae Asset) ---",
            "1. Login to: https://developer.mstock.com",
            "2. Create an App to get your 'API Key' and 'Secret Key'.",
            "3. Client Code: This is your mStock Login ID (e.g., 556677).",
            "4. Password: Your mStock Login Password.",
            "5. Access Token: This expires daily! You verify via the developer portal to get a new one (looks like a long string).",
            "",
            "--- Zerodha (Kite) ---",
            "1. Login to: https://developers.kite.trade",
            "2. Create an App (Cost: ₹2000/month).",
            "3. Copy 'API Key' and 'API Secret'.",
            "4. Access Token is auto-generated by the bot if you have the Secret."
        ]
    },
    "BACKTESTING": {
        "title": "🧪 Backtesting Engine Logic",
        "summary": "Understanding how the Simulation tab works.",
        "how_it_works": [
            "Data Source: Uses Yahoo Finance (yfinance) to fetch historical market data.",
            "Suffix Handling: For Indian stocks, it expects '.NS' (e.g., RELIANCE.NS). If you type 'RELIANCE', it auto-appends '.NS'.",
            "Duration: It fetches 1 year of daily data by default.",
            "Strategy: Simulates a pure RSI Mean Reversion strategy.",
            "  - BUY when RSI < 35 (Oversold)",
            "  - SELL when RSI > 65 (Overbought)",
            "Logic: It iterates through the history day-by-day, calculating Profit/Loss as if you had traded it perfectly according to these rules."
        ]
    },
    "BOT_BEHAVIOR": {
        "title": "🤖 Bot Default Behavior",
        "summary": "What happens when you click 'Start Bot'?",
        "how_it_works": [
            "1. Connectivity Check: It first verifies internet access.",
            "2. Market Status: It checks if the market is Open (09:15 - 15:30 IST). If closed, it waits and counts down.",
            "3. Nifty 50 Filter: If enabled in Settings, it loads the Nifty 50 list.",
            "4. Empty Config: If NO stocks are configured, the bot will run but do nothing. It acts as a passive monitor.",
            "5. Processing: It cycles through your configured stock list every 15-30 seconds, fetching live prices and checking RSI signals."
        ]
    },
    "CAPITAL_LOGIC": {
        "title": "💰 Capital & Balance Logic",
        "summary": "How the bot handles your money vs. settings.",
        "how_it_works": [
            "CASE 1: Settings (₹1L) < Broker Balance (₹10L)",
            " -> The bot respects your Settings (₹1L). It tracks its own 'Virtual Wallet' and refuses to use more than ₹1L.",
            "",
            "CASE 2: Settings (₹10L) > Broker Balance (₹1L)",
            " -> The bot is limited by REALITY. Orders will fail or be rejected by broker if cash is insufficient.",
            " -> Recommendation: Always keep Settings Capital <= Real Broker Balance.",
            "",
            "TRACKING: The bot maintains its own database (trades.db).",
            " -> It calculates P&L based on the trades IT made.",
            " -> It does NOT read your daily broker ledger. It parses live trade confirmations."
        ]
    },
    "API_CAPABILITIES": {
        "title": "🔌 API Power & Off-Market Checks",
        "summary": "What can the mStock/Zerodha API actually see?",
        "how_it_works": [
            "1. Can we check Balances? YES.",
            "   - The API has a 'Funds/Limits' endpoint. We can fetch your available cash anytime.",
            "",
            "2. Can we check Connectivity when Market is CLOSED? YES.",
            "   - Login and User Profile checks work 24/7.",
            "   - We can verify your 'Access Token' is valid even at 3 AM on a Sunday.",
            "",
            "3. P&L Sync vs Position Sync:",
            "   - Positions: We sync LIVE. If you buy on your phone, the bot sees it.",
            "   - History: We assume the bot's database is the 'Strategy Journal'. We don't import random manual trades into the bot's stats."
        ]
    },
    "RSI_STRATEGY": {
        "title": "RSI Mean Reversion (Swing)",
        "summary": "Buy when oversold (RSI < 30), Sell when overbought (RSI > 70).",
        "how_it_works": [
            "The Relative Strength Index (RSI) measures momentum.",
            "Low RSI (< 30) indicates the stock is 'oversold' and might bounce back (BUY signal).",
            "High RSI (> 70) indicates the stock is 'overbought' and might fall (SELL signal).",
            "Best for: Sideways or ranging markets."
        ]
    },
    "SIP_STRATEGY": {
        "title": "SIP (Systematic Investment Plan)",
        "summary": "Buy a fixed amount daily/weekly regardless of price.",
        "how_it_works": [
            "Disciplined investing: Removes emotional decision-making.",
            "Rupee Cost Averaging: You buy more units when price is low, fewer when high.",
            "Long-term wealth creation: Best for blue-chip stocks (Nifty 50).",
            "This bot can automate daily 'Buy at Market Open' logic."
        ]
    },
    "STARTUP_GUIDE": {
        "title": "👋 Welcome to ARUN Bot - Quick Tour",
        "summary": "Everything you need to know to get started.",
        "how_it_works": [
            "1. 📊 Dashboard: Your Command Center. See live positions, market status, and active RSI signals.",
            "2. 📖 Orders: The Order Book. Tracks every pending and executed trade.",
            "3. 🧪 Simulation: The Lab. Test strategies on historical data without risking money.",
            "4. 📜 Logs: The Black Box. Detailed technical records of what the bot is thinking.",
            "5. ⚙️ Settings: The Controls. Set your capital, strategies, and safety limits here.",
            "",
            "⚠️ IMPORTANT: Please read the 'Knowledge Center' guides before trading with real money!"
        ]
    }
}

TOOLTIPS = {
    "portfolio": "Total value of all your stocks plus unused cash.",
    "win_rate": "Percentage of closed trades that ended in profit.",
    "circuit_breaker": "Emergency safety! If the bot loses too much in one day, it stops trading entirely until tomorrow.",
    "paper_trading": "STRICTLY SIMULATED. No real money. Use this to practice!",
    "nifty_filter": "Only allows stocks from India's top 50 companies. Blocks risky penny stocks."
}

def get_strategy_guide(name):
    return STRATEGY_GUIDES.get(name, STRATEGY_GUIDES["RSI Mean Reversion"])

def get_contextual_tip(metric_type, value):
    """
    Returns a smart tip based on the context of a metric.
    Used by the Knowledge Tab in the new UI.
    """
    if metric_type == "RSI":
        if value > 70:
            return "💡 Tip: RSI is OVERBOUGHT (>70). Consider tightening your stop-loss or taking partial profits."
        elif value < 30:
            return "💡 Tip: RSI is OVERSOLD (<30). This could be a good buying opportunity if the trend reverses."
        else:
            return "💡 Tip: RSI is neutral. Wait for a clear signal before entering a new trade."
    
    elif metric_type == "SENTIMENT":
        if "FEAR" in value:
            return "💡 Tip: Market is Fearful. Historically, this is when smart money accumulates quality stocks."
        elif "GREED" in value:
            return "💡 Tip: Market is Greedy. Be cautious. Avoid chasing rallies and stick to your profit targets."
            
    elif metric_type == "PNL":
        if value < 0:
            return "💡 Tip: Don't panic. Stick to your Stop-Loss rules. Emotional exits often lead to regret."
        elif value > 0:
            return "💡 Tip: You're in profit! Consider enabling 'Trailing Stop Loss' to lock in gains."

    return "💡 Tip: Always trade with a plan. Check the 'Strategies' tab for more details."
