
# Sector Mapping for Nifty 50
SECTOR_MAP = {
    # FINANCIAL SERVICES
    "HDFCBANK": "FINANCIALS", "ICICIBANK": "FINANCIALS", "SBIN": "FINANCIALS", "AXISBANK": "FINANCIALS",
    "KOTAKBANK": "FINANCIALS", "INDUSINDBK": "FINANCIALS", "BAJFINANCE": "FINANCIALS", "BAJAJFINSV": "FINANCIALS",
    "HDFCLIFE": "FINANCIALS", "SBILIFE": "FINANCIALS",

    # IT
    "TCS": "IT", "INFY": "IT", "HCLTECH": "IT", "KAJARIACER": "IT", "TECHM": "IT", "WIPRO": "IT", "LTIM": "IT",

    # OIL GAS & CONSUMABLE FUELS
    "RELIANCE": "ENERGY", "ONGC": "ENERGY", "BPCL": "ENERGY", "COALINDIA": "ENERGY", "NTPC": "ENERGY", "POWERGRID": "ENERGY",

    # FMCG
    "ITC": "FMCG", "HINDUNILVR": "FMCG", "NESTLEIND": "FMCG", "BRITANNIA": "FMCG", "TATACONSUM": "FMCG",

    # AUTO
    "MARUTI": "AUTO", "M&M": "AUTO", "TATAMOTORS": "AUTO", "BAJAJ-AUTO": "AUTO", "EICHERMOT": "AUTO", "HEROMOTOCO": "AUTO",

    # PHARMA
    "SUNPHARMA": "PHARMA", "DRREDDY": "PHARMA", "CIPLA": "PHARMA", "DIVISLAB": "PHARMA", "APOLLOHOSP": "PHARMA",

    # METALS
    "TATASTEEL": "METALS", "HINDALCO": "METALS", "JSWSTEEL": "METALS",

    # OTHERS
    "ADANIENT": "OTHERS", "ADANIPORTS": "OTHERS", "LT": "INFRA", "ULTRACEMCO": "INFRA", "GRASIM": "INFRA",
    "ASIANPAINT": "CONSUMER", "TITAN": "CONSUMER", "BHARTIARTL": "TELECOM", "UPL": "AGRO"
}

def get_sector(symbol):
    return SECTOR_MAP.get(symbol, "OTHERS")
